start /b gulp release --conf=.\conf\nagano\ --dest=R:\embed-hosting\nagano\v1.3\
exit
start /b gulp release --conf=.\conf\nagoya\ --dest=R:\embed-hosting\trial\nagoya\
start /b gulp release --conf=.\conf\yoshida\ --dest=R:\embed-hosting\yoshida\
start /b gulp release --conf=.\conf\trial\kagoshima\ --dest=R:\embed-hosting\trial\kagoshima\
start /b gulp release --conf=.\conf\trial\fukui\ --dest=R:\embed-hosting\trial\fukui\
start /b gulp release --conf=.\conf\trial\unica\ --dest=R:\embed-hosting\trial\unica\
start /b gulp release --conf=.\conf\trial\mie\ --dest=R:\embed-hosting\trial\mie\
start /b gulp release --conf=.\conf\trial\osaka\ --dest=R:\embed-hosting\trial\osaka\
start /b gulp release --conf=.\conf\trial\kumamoto\ --dest=R:\embed-hosting\trial\kumamoto\
start /b gulp release --conf=.\conf\trial\nagasaki\ --dest=R:\embed-hosting\trial\nagasaki\
start /b gulp release --conf=.\conf\trial\akita\ --dest=R:\embed-hosting\trial\akita\
start /b gulp release --conf=.\conf\trial\oita\ --dest=R:\embed-hosting\trial\oita\
start /b gulp release --conf=.\conf\trial\nara\ --dest=R:\embed-hosting\trial\nara\
start /b gulp release --conf=.\conf\trial\tottori\ --dest=R:\embed-hosting\trial\tottori\
start /b gulp release --conf=.\conf\trial\shizuoka\ --dest=R:\embed-hosting\trial\shizuoka\
start /b gulp release --conf=.\conf\trial\fukushima\ --dest=R:\embed-hosting\trial\fukushima\
start /b gulp release --conf=.\conf\trial\chiba\ --dest=R:\embed-hosting\trial\chiba\
start /b gulp release --conf=.\conf\trial\kanagawa\ --dest=R:\embed-hosting\trial\kanagawa\
start /b gulp release --conf=.\conf\trial\ujitawara\ --dest=R:\embed-hosting\trial\ujitawara\
start /b gulp release --conf=.\conf\trial\kochi\ --dest=R:\embed-hosting\trial\kochi\
start /b gulp release --conf=.\conf\trial\aichi\ --dest=R:\embed-hosting\trial\aichi\
start /b gulp release --conf=.\conf\trial\ibaraki\ --dest=R:\embed-hosting\trial\ibaraki\
start /b gulp release --conf=.\conf\trial\saitama\ --dest=R:\embed-hosting\trial\saitama\
start /b gulp release --conf=.\conf\tokoton\ --dest=R:\embed-hosting\tokoton\
start /b gulp release --conf=.\conf\ovcic\ --dest=R:\embed-hosting\ovcic\
start /b gulp release --conf=.\conf\ogori\ --dest=R:\embed-hosting\ogori\
start /b gulp release --conf=.\conf\kyoto-private\ --dest=R:\embed-hosting\kyoto\v1.3\private\
start /b gulp release --conf=.\conf\kyoto-public\ --dest=R:\embed-hosting\kyoto\v1.3\public\
start /b gulp release --conf=.\conf\kagoshima-public\ --dest=R:\embed-hosting\kagoshima\v1.3\public\
start /b gulp release --conf=.\conf\kagoshima-private\ --dest=R:\embed-hosting\kagoshima\v1.3\private\
